#!/bin/sh
. "$(dirname "$0")/husky.sh"

echo '------PRE-COMMIT HOOK START------'
echo '------RUNNING PRE COMMIT HOOK------'

# Check if the code needs formatting
if ! dotnet format --verbosity diagnostic --verify-no-changes; then
  echo '------CODE NEEDS FORMATTING. RUNNING DOTNET FORMAT.....------'
  dotnet format --verbosity diagnostic
  echo '------CODE FORMATED, CHECK CHANGED FILES IN GIT CHANGES AND COMMIT AGAIN------'
  exit 1
fi


# Build the project
if ! dotnet build --no-restore; then
  echo '------BUILED-FAILED------'
  echo '------PRE-COMMIT HOOK CANCELED------'
  exit 1
fi

# Test the project
if ! dotnet test --verbosity normal --no-restore; then
  echo '------TEST-FAILED------'
  echo '------PRE-COMMIT HOOK CANCELED------'
  exit 1
fi

echo '------PRE-COMMIT HOOK EXECUTED SUCCESSFULLY------'
echo '------PRE-COMMIT HOOK END------'
